### ISSUE TITLE
Difference from ArrayVec

### ISSUE THREAD

**Issue by matklad** [Alexhuszagh/rust-stackvector#1]
Hi!

From the casual look, this crate seems pretty similar to `arrayvec` whose [`ArrayVec`](https://docs.rs/arrayvec/0.4.11/arrayvec/struct.ArrayVec.html) type corresponds pretty directly to `StackVec`. 

Perhaps it makes sense to explain the difference between the two crates in Readme?

**Comment by Alexhuszagh** [comment]
@matklad Done as-of 128954b7de47fd227730ca0ac6079d3797333a8e. I may see if I can port some of these differences to ArrayVec as well, since the support ArrayVec has for the Vec API has increased dramatically since when I wrote this crate.

Thanks.
